[platformio]
default_envs              = esp32s3zero

[env]
  monitor_speed           = 115200
  upload_speed            = 921600
  lib_ldf_mode            = chain+
  lib_deps                = https://github.com/bblanchon/ArduinoJson.git#7.4.x

[env:esp32s3zero]
  platform                = espressif32
  board                   = esp32-s3-devkitc-1
  framework               = arduino
  upload_protocol         = esptool
  debug_tool              = esp-builtin

  ; ESP32-S3-Zero / ESP32-FH4R2: 4 MB embedded QIO flash + 2 MB QSPI PSRAM.
  board_upload.flash_size = 4MB
  board_upload.maximum_size = 4194304
  board_build.flash_size  = 4MB
  board_build.flash_mode  = qio
  board_build.psram_type  = qspi
  board_build.arduino.memory_type = qio_qspi

  board_build.partitions  = partitions.csv
  board_build.filesystem  = littlefs

  build_flags             = -D ARDUINOJSON_USE_LONG_LONG=0
                            -D ARDUINOJSON_USE_DOUBLE=0
                            -D ARDUINOJSON_ENABLE_STD_STRING=0
                            -D ARDUINOJSON_ENABLE_STD_STREAM=0
                            -D ARDUINOJSON_ENABLE_ARDUINO_STREAM=0
                            -D ARDUINOJSON_ENABLE_ARDUINO_PRINT=0
                            -D ARDUINOJSON_ENABLE_PROGMEM=0
                            -D ARDUINOJSON_DEFAULT_NESTING_LIMIT=5
                            -D HIDPAD_FIRMWARE_VERSION=\"0.5.1\"
                            -D BOARD_HAS_PSRAM
                            -D ARDUINO_USB_MODE=0
                            -D ARDUINO_USB_CDC_ON_BOOT=0
                            -D NDEBUG
                            -DCORE_DEBUG_LEVEL=0
                            -Os
                            -flto
                            -fno-exceptions
                            -fno-stack-protector
                            -fno-unwind-tables
                            -fno-asynchronous-unwind-tables
                            -Wall
                            -Wno-unused-function
                            -ffunction-sections
                            -fdata-sections
                            -Wl,--gc-sections
                            -Wl,-Map=output.map
                            -Wl,--cref
  build_unflags           = -fexceptions
                            -fno-lto
                            -ggdb
                            -fstack-protector
                            -DARDUINO_USB_MODE=1
